import { CompletedOrder } from "./lists";

export const completedOrders: CompletedOrder[] = [
  {
    id: 1,
    courseName: "Yoga for Kids Relaxation, Emotional Well-being With Poses",
    purchaseNumber: "PURCHASE_KODU7M20241009",
    createdAt: "09/10/2024",
    studentName: "Lê Minh Trung",
    instructorName: "Ngô Thị Tuyết Trúc",
    pricePaid: "324,350",
    discount: "35",
  },
  {
    id: 2,
    courseName: "Course 1",
    purchaseNumber: "PURCHASE_WS0NWG20241009",
    createdAt: "09/10/2024",
    studentName: "Lê Minh Trung",
    instructorName: "Lưu Ka Ka",
    pricePaid: "180,000",
    discount: "10",
  },
  {
    id: 3,
    courseName: "Complete Guitar Lessons System - Beginner to Advanced",
    purchaseNumber: "PURCHASE_U7VISM20240804",
    createdAt: "04/08/2024",
    studentName: "Lê Minh Trung",
    instructorName: "Ngô Thị Tuyết Trúc",
    pricePaid: "489,650",
    discount: "65",
  },
  {
    id: 4,
    courseName: "Financial Analysis and Financial Modeling using MS Excel",
    purchaseNumber: "PURCHASE_OTD6NZ20240802",
    createdAt: "02/08/2024",
    studentName: "Lê Minh Trung",
    instructorName: "Ngô Thị Tuyết Trúc",
    pricePaid: "461,230",
    discount: "23",
  },
  {
    id: 5,
    courseName: "100 Days of Code: The Complete Python Pro Bootcamp",
    purchaseNumber: "PURCHASE_CAX1B220240801",
    createdAt: "02/08/2024",
    studentName: "Lê Minh Trung",
    instructorName: "Phan Hồng Yến Thảo",
    pricePaid: "1,250,000",
    discount: "50",
  },
  {
    id: 6,
    courseName: "Digital Marketing & Advertising Masterclass",
    purchaseNumber: "PURCHASE_P4LTKV20240801",
    createdAt: "02/08/2024",
    studentName: "Lê Minh Trung",
    instructorName: "Phan Hồng Yến Thảo",
    pricePaid: "310,560",
    discount: "76",
  },
  {
    id: 7,
    courseName: "Operating System Crash Course For Beginners",
    purchaseNumber: "PURCHASE_DCBUKS20240801",
    createdAt: "02/08/2024",
    studentName: "Lê Minh Trung",
    instructorName: "Phan Hồng Yến Thảo",
    pricePaid: "299,250",
    discount: "25",
  },
  {
    id: 8,
    courseName: "The Complete Graphic Design Theory for Beginners Course",
    purchaseNumber: "PURCHASE_FMNVX_20240801",
    createdAt: "01/08/2024",
    studentName: "Lê Minh Trung",
    instructorName: "Lưu Ka Ka",
    pricePaid: "1,139,400",
    discount: "40",
  },
];
